env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - XCPROJ="-workspace RxAutomaton.xcworkspace -scheme RxAutomaton"

osx_image: xcode8.2

matrix:
  include:
    - os: osx
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -destination 'platform=OS X' ENABLE_TESTABILITY=YES $XCPROJ | xcpretty
      env:
        - JOB=xcodebuild-macOS

    - os: osx
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.0' ENABLE_TESTABILITY=YES $XCPROJ | xcpretty
      env:
        - JOB=xcodebuild-iOS

    - os: osx
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -destination 'platform=tvOS Simulator,name=Apple TV 1080p' ENABLE_TESTABILITY=YES $XCPROJ | xcpretty
      env:
        - JOB=xcodebuild-tvOS

    - os: osx
      language: objective-c
      script:
        - set -o pipefail
        - xcodebuild build -destination 'platform=watchOS Simulator,name=Apple Watch - 38mm' $XCPROJ | xcpretty
      env:
        - JOB=xcodebuild-watchOS

    - os: osx
      script:
        - pod repo update --silent
        - pod lib lint --allow-warnings
      env: JOB=pod-lint

    - os: osx
      language: generic
      script:
        - swift build
      env:
        - JOB=swiftpm-mac

    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - mv .Package.test.swift Package.swift
        - swift build
        - swift test
      env: JOB=swiftpm-linux
